### ISSUE TITLE
Invalid QML singleton type name "sps"; type names must begin with an uppercase letter 

### ISSUE THREAD

**Issue by SwyssX** [stefanbesler/QADS#2]
Hello Stefan,

I found a small bug:

same here: https://github.com/Maldela/fancontrol-gui/issues/12

Singleton/Type names must begin with an upper case letter since Qt 5.10

I always got a M304 QML error when I wanted to make the Back-Ends Link in the Designer.

I changed line 17 in Main.cpp    qmlRegisterSingletonType<Tc3Value>("Sps", 1, 0, "Spsvalue");
and changed sps to Sps on all other places where it is used.
Now I can create the link in Designer.
But I am now looking how to link it properly to a specific property.
It would be real helpfull if you could just post a little example how to link in
designer to update a twincat variable and also if it is changed in designer how to bring the
change back to twincat.

Another small bug:

in qads.pro line 13 the libws2_32 is not needed. As the winsock is not used by the Twincat .dll.
It is only included in Mingw so if the line is in you get linker Errors in all the MSVC Compilers.

You did amazing work with this libary. Big thanks Stefan

**Comment by stefanbesler** [comment]
in order to make this work with qtdesigner you have to modify qads a bit. So far, I see qads more as a proof of concept for using ads within qml. If you want it to work with qwidgets you have to add new signals (valueChanged(float), valueChanged(double)).

The TcDriver.h is merely an example of how to implement a connection between ads and qml. 
If you want the make real heavy duty visualization you might have to take a completely different route anyway. It is much faster to connect to a big struct containing loads of plc variables (even > 100 kB worth of RAM). You can do this by using the datasize_bytes parameter of Tc3Value. Converting PLC structs to C++ objects is a whole different story though - I wouldn’t recommend doing this by manually 😁

**Comment by SwyssX** [comment]
As the .ui.qml designer files do not allow Java script in properties it guess it is better to
use the editable .qml of the form and add the sps variable handling there manually :)
